Fix: Issue with compression/format
Was getting this error:

Error: copying image 1/2 from manifest list: compression using zstd:chunked required together with format application/vnd.docker.distribution.manifest.v2+json, which does not support it

It must no longer be required.